import os
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
)
from datetime import datetime
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


def generate_report(
    filename,
    concept,
    transcript,
    similarity,
    filler_ratio,
    pause_ratio,
    rms_energy,
    score,
    feedback,
    waveform_path,
) -> str:
    """
    Generate PDF Evaluation Report.
    Handles missing waveform images, ReportLab style errors, and locked files.
    """
    doc_filename = filename

    styles = getSampleStyleSheet()
    elements = []

    # Title Banner
    elements.append(
        Paragraph(
            "Voice-Based Concept Understanding Analyser",
            styles["Title"]
        )
    )
    elements.append(
        Paragraph(
            f"Generated On : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 20))
    elements.append(
        Paragraph(
            "Evaluation Report",
            styles["Heading1"]
        )
    )

    elements.append(Spacer(1, 20))

    # Reference Concept
    elements.append(
        Paragraph(f"<b>Reference Concept:</b><br/>{concept}", styles["BodyText"])
    )

    elements.append(Spacer(1, 12))

    # Student Transcription
    elements.append(Paragraph("<b>Student Transcription</b>", styles["Heading2"]))
    elements.append(Paragraph(transcript if transcript else "(No transcript text detected)", styles["BodyText"]))

    elements.append(Spacer(1, 15))

    # Audio Visualization
    elements.append(Paragraph("<b>Audio Visualization</b>", styles["Heading2"]))
    if waveform_path and os.path.exists(waveform_path):
        try:
            elements.append(Image(waveform_path, width=450, height=150))
        except Exception:
            elements.append(Paragraph("<i>Waveform unavailable.</i>", styles["BodyText"]))
    else:
        elements.append(Paragraph("<i>Waveform unavailable.</i>", styles["BodyText"]))

    elements.append(Spacer(1, 20))

    # Metrics Table
    data = [
        ["Evaluation Metric", "Result"],
        ["Semantic Similarity", f"{similarity:.2f}"],
        ["Filler Word Ratio", f"{filler_ratio:.3f}"],
        ["Pause Ratio", f"{pause_ratio:.3f}"],
        ["Average RMS Energy", f"{rms_energy:.3f}"],
        ["Final Understanding Score", f"{score}/100"],
        ["Understanding Level", feedback],
    ]

    table = Table(data)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 20))

    # Interpretation
    elements.append(Paragraph("<b>Interpretation</b>", styles["Heading2"]))
    elements.append(
        Paragraph(
            "The evaluation score is generated by combining semantic similarity, filler-word analysis, pause ratio and speech confidence metrics.",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 12))

    # Feedback
    elements.append(Paragraph("<b>Overall Feedback</b>", styles["Heading2"]))
    elements.append(Paragraph(feedback if feedback else "No feedback available.", styles["BodyText"]))

    elements.append(Spacer(1, 20))

    # Footer (Fixing the styles["Italic"] KeyError by using HTML tags in BodyText)
    elements.append(
        Paragraph(
            "<i>Generated automatically by Voice-Based Concept Understanding Analyser</i>",
            styles["BodyText"],
        )
    )

    # Build the document, handling permission locks gracefully
    try:
        doc = SimpleDocTemplate(doc_filename)
        doc.build(elements)
    except PermissionError:
        # File is locked, append timestamp to make it unique
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        name_part, ext_part = os.path.splitext(filename)
        doc_filename = f"{name_part}_{timestamp}{ext_part}"
        doc = SimpleDocTemplate(doc_filename)
        doc.build(elements)

    return doc_filename
