from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
)
from datetime import datetime
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


def generate_report(
    filename,
    concept,
    transcript,
    similarity,
    filler_ratio,
    pause_ratio,
    rms_energy,
    score,
    feedback,
    waveform_path,
):
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []
    

    elements.append(
    Paragraph(
        "Voice-Based Concept Understanding Analyser",
        styles["Title"]
        )
    )
    elements.append(
    Paragraph(
        f"Generated On : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
        styles["BodyText"]
    )
)

    elements.append(Spacer(1,20))
    elements.append(
    Paragraph(
        "Evaluation Report",
        styles["Heading1"]
        )
    )

    elements.append(Spacer(1,20))

    elements.append(
        Paragraph(f"<b>Reference Concept:</b><br/>{concept}", styles["BodyText"])
    )

    elements.append(Spacer(1, 12))

    elements.append(Paragraph("<b>Student Transcription</b>", styles["Heading2"]))

    elements.append(Paragraph(transcript, styles["BodyText"]))

    elements.append(Spacer(1, 15))

    elements.append(Paragraph("<b>Audio Visualization</b>", styles["Heading2"]))

    elements.append(Image(waveform_path, width=450, height=150))

    elements.append(Spacer(1, 20))

    data = [
        ["Evaluation Metric", "Result"],
        ["Semantic Similarity", f"{similarity:.2f}"],
        ["Filler Word Ratio", f"{filler_ratio:.3f}"],
        ["Pause Ratio", f"{pause_ratio:.3f}"],
        ["Average RMS Energy", f"{rms_energy:.3f}"],
        ["Final Understanding Score", f"{score}/100"],
        ["Understanding Level", feedback],
    ]

    table = Table(data)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("<b>Interpretation</b>", styles["Heading2"]))

    elements.append(
        Paragraph(
            "The evaluation score is generated by combining semantic similarity, filler-word analysis, pause ratio and speech confidence metrics.",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 12))

    # elements.append(Paragraph(f"<b>Overall Feedback:</b> {feedback}", styles["BodyText"]))
    elements.append(Paragraph("<b>Overall Feedback</b>", styles["Heading2"]))

    elements.append(Paragraph(feedback, styles["BodyText"]))

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "Generated automatically by Voice-Based Concept Understanding Analyser",
            styles["Italic"],
        )
    )
    doc.build(elements)

    return filename
